### ISSUE TITLE
Simpler settings web interface

### ISSUE THREAD

**Issue by revk** [revk/ESP32-RevK#12]
- [x] Make the web socket based settings take a JSON settings object from webscoket and pass directly to `revk_settings()` - making code much simpler and easier to expand later. JS side needs to populate correctly with correct field names.
- [x] Make the JSON post send all fields in the form
- [x] Parse non web socket post/get, and if necessary handle escaping, making a JSON setting string to then pass to `revk_settings()` directly.

Only concern being this allows all settings via web socket or get/post with not authentication. But given we allow mqtt settings this way and then via mqtt you can change all settings, this is not an extra security risk. We have an option to restrict web access, so.

- [x] Check restricted web access is properly applied to the websocket or get/post controls as well.

**Comment by revk** [comment]
The restrict is applied at the app level, including "/wifi" or not.

Done

**Comment by Sonic-Amiga** [comment]
I see you implemented a direct query-2-json converter, correct ?
Thank you for your great cooperation; my project is dormant at the moment because i'm satisfied with how it currently functions; so i am moving on to other things. Nobody except myself is interested anyways, so broken OTA can wait.

And i'm just too lazy to disassemble my first working AC and remove original online controller for experimentation, to figure out sleep vs auto finally. Yes, appears not trivial, dumping didn't really help.

**Comment by revk** [comment]
Yes. Simple (all fields are strings) but does the job.
